# Generated by Django 3.2.7 on 2021-09-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('faculty', 'faculty'), ('hr', 'hr'), ('counselor', 'counselor')], default='faculty', max_length=40),
        ),
    ]
