# Generated by Django 3.2.7 on 2021-09-22 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20210917_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('topic_status', models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed')], default='in_progress', max_length=100)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.batch')),
            ],
        ),
    ]
